### ISSUE TITLE
ITKIOOpenSlide functionality is not implemented

### ISSUE THREAD

**Issue by nslay** [InsightSoftwareConsortium/ITKIOOpenSlide#1] opened 2016-03-27 01:17 UTC
I found this ImageIO and was surprised that none of it was implemented.

I went ahead and implemented it myself. I've added abilities to support all of OpenSlide's features in a way that is flexible enough for ITK. I've tested it for accessing level (!= 0) and associated images.

However, I'm still experimenting with ITK IO streaming to deal with level 0 images! ITK seems to use 32 bit integers for sizes and that can cause overflows (e.g. images being 60000 x 70000). I added sanity checks that try to catch these problems.

https://github.com/nslay/ITKIOOpenSlide

Does it look good? Do you want to pull it?

**Comment by thewtex** [comment] 2016-03-27 03:02
@nslay Thanks for your work and potential contributions! 

You have been invited to the team that has push permissions for the repository. You can create a pull request and other interested members like @siavashk or @dhandeo could review it. If they do not have time to review it, you can push the updates directly.

Then, add the repository to ITK as a Remote Module as documented here:

  http://www.itk.org/Wiki/ITK/Policy_and_Procedures_for_Adding_Remote_Modules

ITK currently only uses 32 bit integers for sizes on Window if the CMake option ITK_USE_64BITS_IDS is OFF.  This may be switched to ON by default for ITK 4.10 if this patch is merged:

  http://review.source.kitware.com/#/c/20866/

**Comment by thewtex** [comment] 2016-03-27 03:03
CC: @curtislisle

**Comment by nslay** [comment] 2016-03-28 12:59
Hi Matt,
Thanks for the prompt response. You'll have to forgive me, but I'm
relatively new to working with git. I'll try to follow all policies in a
timely fashion.

Perfect, I'll be sure to try ITK_USE_64BITS_IDS on Windows. I was pretty
surprised by the overflow problems I experienced. I'm relieved that ITK
already addressed this.

Best regards,
Nathan Lay

**Comment by blowekamp** [comment] 2016-03-28 13:34
I have successfully streamed quire large images with the 32-bits build.

Is this size computation in the ImageIO? In several IO's I wrote that is a size type that is used for file offsets. In some cases when doing the size computation the inducies should be cast to this type before multiplication. If you have a specific location I could better advise.

In the StreamingImageIOBase, which is designed to directly deal with files std::stream size is used [1]. I have been able to stream read 100GB files on 32-bit systems with this ImageIO class.

It recent work done with TiffImageIO size_t was use frequently. [2] This approach helps on all 64-bit systems but not 32-bit. 

HTH,
Brad

[1] https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/ImageBase/src/itkStreamingImageIOBase.cxx#L49-L73
[2] https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/TIFF/src/itkTIFFImageIO.cxx

**Comment by nslay** [comment] 2016-03-28 14:10
I've seen the problem appear in ImageIORegion, particularly:
ImageIORegion::GetNumberOfPixels()
when using ITK 4.8.2.

If the IO region's size is small enough so that the product of dimensions fits in 32 bits, it might work. Although, I've not had luck getting the streaming to work yet.

**Comment by nslay** [comment] 2016-03-28 14:36
OK,  I stand corrected.
I connected a reader to a writer and called SetNumberOfStreamDivisions() on the writer and got it to work. This is something I missed when reading:
http://www.kitware.com/media/html/IOStreamingInITK.html

EDIT:
It was able to stream ITKIOOpenSlide, woo! My images are about ~18GB.
I suspected that some sort of offset computation might overflow still, but it does not seem to be the case.

As a side problem, the MetaDataDictionary I form could contain values with = signs. This appears to cause problems for MetaImageIO.

For example:
`openslide.comment = Aperio Image Library v12.0.15 
78368x62379 [0,100 75207x62279] (240x240) JPEG/RGB Q=30|AppMag = 20|StripeWidth = 992|Time Zone = GMT-04:00|Parmset = 2x3 Support|MPP = 0.4972|Left = 8.027027|Top = 40.774609|LineCameraSkew = 0.000425|LineAreaXOffset = -0.000018|LineAreaYOffset = -0.012135|Focus Offset = -0.000500|Exposure Time = 109|Exposure Scale = 0.000001|DisplayColor = 0|OriginalWidth = 78368|OriginalHeight = 62379|ICC Profile = ScanScope v1`

MetaImageIO does not like this in its header at all.

**Comment by brianhelba** [comment] 2016-03-28 16:06
You may be interested to see that a similar integration to add OpenSlide support to VTK is currently in review at: https://gitlab.kitware.com/vtk/vtk/merge_requests/1235

If there are any opportunities to share code segments, or at least clever design features, that would be great.

Ping @dhandeo , the author of the VTK feature.

**Comment by nslay** [comment] 2016-03-28 17:08
I found the repository:
https://gitlab.kitware.com/dhanannjay-deo/vtk/tree/dev/openslide-reader/Domains/Microscopy

I could definitely use the test data. 

I'm reading his code to see if there are any details I missed.

**Comment by siavashk** [comment] 2016-03-28 17:13
@thewtex, @nslay  I am no longer working in digital pathology, but I am interested in the solution. I will do some testing when I come back from vacation.

**Comment by siavashk** [comment] 2016-03-29 21:41
@nslay When I try to build ITK with the external module, I get a number of errors (see attached log.txt). The first error is:

/home/siavash/ITK/Modules/External/ITKIOOpenSlide/src/itkOpenSlideImageIO.cxx:266:12: error: explicit specialization in non-namespace scope ‘class itk::OpenSlideWrapper’
   template<>

The build succeeds if I modify line 266 to the following: 
`template<typename ValueType>`

[log.txt](https://github.com/InsightSoftwareConsortium/ITKIOOpenSlide/files/194373/log.txt)

**Comment by nslay** [comment] 2016-03-29 22:11
Thanks @siavashk

Try removing `template<>` from line 266.

**Comment by siavashk** [comment] 2016-03-29 22:14
@nslay I can verify that it builds. Do you have sample data so I can test basic IO? I no longer have access to pathology images.

**Comment by dhandeo** [comment] 2016-03-29 22:21
Openslide website provides freely distributable test images at
http://openslide.cs.cmu.edu/download/openslide-testdata/

Many pathology images formats may have versions (and source specific
variations), hence even if openslide claims to support, actual success may
vary.

On Tue, Mar 29, 2016 at 6:14 PM, Siavash Khallaghi <notifications@github.com

> wrote:
> 
> @nslay https://github.com/nslay I can verify that it builds. Do you
> have sample data so I can test basic IO? I no longer have access to
> pathology images.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/InsightSoftwareConsortium/ITKIOOpenSlide/issues/1#issuecomment-203135498

## 

BEST Regards,

## 

Dhanannjay (D'Jay) Deo

[ नासतो विद्यते भावो नाभावो विद्यते सतः ।
  Nothing unreal exists, nothing real can be threatened |
  (Bhagawad Geeta 2:16) ]

**Comment by nslay** [comment] 2016-03-29 22:30
So far, I've tried this on Windows with VS 2015. I'm going to join you (@siavashk) in trying this on Linux.

I have pathology data, but I'm not sure if I can share it.

Thanks @dhandeo, I'll check those out.

**Comment by siavashk** [comment] 2016-03-29 22:55
@nslay I am using the open data that @dhandeo purposed. So far I can't IO. The process terminates with "Segmentation fault (core dumped)" when `reader->Update();` is called.

I am just trying to read an image through a reader and display the spacing:

```
typedef itk::Image< double, 2 >  ImageType;
typedef itk::ImageFileReader<ImageType> ReaderType;
ReaderType::Pointer reader = ReaderType::New();
reader->SetFileName(argv[1]);

try
{
   reader->Update();
}
catch( itk::ExceptionObject & err )
{
  std::cerr << "ExceptionObject caught !" << std::endl;
   std::cerr << err << std::endl;
  return EXIT_FAILURE;
}

std::cout << reader->GetOutput()->GetSpacing()[0] << std::endl;`
```

**Comment by nslay** [comment] 2016-03-29 22:58
Hi @siavashk 
Can you query the image dimensions directly from the IO? If it's a large image, you could be running out of memory.

Or try a different level.

**Comment by siavashk** [comment] 2016-03-29 23:04
@nslay I am using CMU-1-Small-Region.svs from http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio. The entire image is 1.9 MB. My Linux box has 16 GB of RAM. I doubt memory is the issue.

The core dump happens on `reader->Update();` So I can't access `reader->GetOutput();` Could it be that I am not linking against the correct OpenSlide static library? Right now I am linking against openslide/common/libopenslide-common.a.

**Comment by siavashk** [comment] 2016-03-29 23:09
@nslay Can you verify that you can read images in that folder? This can help us narrow down if the problem is with the data, with the code, or my build.

**Comment by nslay** [comment] 2016-03-29 23:18
OK, I can reproduce your segfault on Linux. Let me see what's going on.

The ImageIO itself provides a way to query information about the specified file. Just call ReadImageInformation() and query one of the ImageIOBase functions to get spacing, dimension, etc...

**Comment by siavashk** [comment] 2016-03-29 23:31
@nslay I can query with ReadImageInformation(), for example for the image above, I can retrieve the following information: 

Pixel Type is unsigned_char
numDimensions: 3
component size: 1
pixel type (string): rgba
pixel type: 3
size: 2220, 2967, 2

**Comment by nslay** [comment] 2016-03-29 23:32
numDimensions: 3?

How did that happen. I call SetNumberOfDimensions(2) in the ImageIO constructor and ReadImageInformation() function.

**Comment by nslay** [comment] 2016-03-29 23:40
I get a crash in openslide.so in aperio_open() in the backtrace.
I also can't get openslide-write-png (a utility that comes with OpenSlide) to write a small portion of the image. Something is wrong with my libopenslide library.

Can you verify that your OpenSlide is working properly?

**Comment by siavashk** [comment] 2016-03-29 23:42
This is my code for reading image info: 

```
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkMetaImageIO.h"

int main(int argc, char *argv[])
{
  if( argc < 2 )
    {
    std::cerr << "Usage: " << std::endl;
    std::cerr << argv[0] << " inputImageFile" << std::endl;
    return EXIT_FAILURE;
    }

  typedef itk::ImageIOBase::IOComponentType ScalarPixelType;

  itk::ImageIOBase::Pointer imageIO =
        itk::ImageIOFactory::CreateImageIO(
            argv[1], itk::ImageIOFactory::ReadMode);
  if( !imageIO )
  {
    std::cerr << "Could not CreateImageIO for: " << argv[1] << std::endl;
    return EXIT_FAILURE;
  }
  imageIO->SetFileName(argv[1]);
  imageIO->ReadImageInformation();
  const ScalarPixelType pixelType = imageIO->GetComponentType();
  std::cout << "Pixel Type is " << imageIO->GetComponentTypeAsString(pixelType) // 'double'
            << std::endl;
  const size_t numDimensions =  imageIO->GetNumberOfDimensions();
  std::cout << "numDimensions: " << numDimensions << std::endl; // '2'

  std::cout << "component size: " << imageIO->GetComponentSize() << std::endl; // '8'
  std::cout << "pixel type (string): " << imageIO->GetPixelTypeAsString(imageIO->GetPixelType()) << std::endl; // 'vector'
  std::cout << "pixel type: " << imageIO->GetPixelType() << std::endl; // '5'
  std::cout << "size: " << imageIO->GetDimensions(0) << ", " << imageIO->GetDimensions(1) << ", " << imageIO->GetDimensions(2) << std::endl; // '5'

  return EXIT_SUCCESS;
}
```

**Comment by siavashk** [comment] 2016-03-29 23:52
@nslay I am having trouble with Openslide too. Running openslide-write-png and openslide-show-properties results in the following: ./CMU-1-Small-Region.svs: Not a file that OpenSlide can recognize

I am running them with the following options: 
./openslide-write-png ./CMU-1-Small-Region.svs 1 1 0 20 20 ./output.png
./openslide-show-properties ./CMU-1-Small-Region.svs

**Comment by nslay** [comment] 2016-03-30 00:07
Woo, I compiled the latest tiff and OpenJPEG2 and then re-compiled OpenSlide and I can write a level 3 image with ITK.

To configure OpenSlide, export environment LIBTIFF_CFLAGS, LIBTIFF_LIBS, OPENJPEG2_CFLAGS and OPENJPEG2_LIBS

Then be sure to export LD_LIBRARY_PATH accordingly or else OpenSlide picks up the system versions of tiff and jpeg2.

**Comment by nslay** [comment] 2016-03-30 00:15
I can also run on CMU-1-Small-Region.svs

Try compiling OpenSlide against the latest TIFF and OpenJPEG.
Also be sure to run `ldd libopenslide.so` to make sure it's pulling in your versions rather than the system's.

I will also commit fixes for the annoying signed/unsigned comparison warnings.

**Comment by siavashk** [comment] 2016-03-30 00:22
@nslay, thanks. I will see if I can get it to work.

**Comment by nslay** [comment] 2016-03-30 00:22
Lastly, here's my sandbox code.
[DownsampleSlide.txt](https://github.com/InsightSoftwareConsortium/ITKIOOpenSlide/files/194521/DownsampleSlide.txt)

I originally wrote it to downsample my pathology images. But now it has lots of preprocessors for testing various things.

**Comment by nslay** [comment] 2016-03-30 14:11
If anyone wants to test ITKIOOpenSlide, I've pushed an example that exhaustively dumps slide information/images with example output for one of the test data sets.

https://github.com/nslay/ITKIOOpenSlide/tree/master/example

This example uses almost all features available in ITKIOOpenSlide.

**Comment by thewtex** [comment] 2016-04-06 15:14
@nslay you're making great progress!

Would you like to upload the testing images here?:

  https://midas3.kitware.com/midas/community/12

We can then add the content link (.md5) files to the repository to be used in the module tests. The file upload process / content link download process is described here:

  http://itk.org/ITKExamples/Documentation/Contribute/UploadBinaryData.html

The files could be uploaded to this folder:

  https://midas3.kitware.com/midas/folder/13507

Please let me know your account name, and I will add upload permissions to the account.

**Comment by nslay** [comment] 2016-04-07 00:21
Hi Matthew,
I've signed up for midas with account name "Nathan Lay"

Here's a link to my account:
https://midas3.kitware.com/midas/user/409

I will study the documentation you've provided and upload some test data.

**Comment by thewtex** [comment] 2016-04-07 00:42
Great!

Could you please "Join" the ITK Community?

  https://midas3.kitware.com/midas/community/12

After your user has joined, I can give the account upload permissions.

**Comment by nslay** [comment] 2016-04-07 00:45
I have joined. Thanks.

**Comment by thewtex** [comment] 2016-04-07 00:47
Perfect, thanks! You now have upload permissions.

**Comment by nslay** [comment] 2016-04-07 01:34
I successfully tested this module on FreeBSD 10-STABLE (~10.3) using the system compiler clang 3.4.1. Clang warns about type punning unsigned char \* into uint32_t *.Otherwise, all of ITK 4.9 and ITKIOOpenSlide compiles cleanly.

**Comment by thewtex** [comment] 2016-04-07 01:44
Excellent! Pull request?

**Comment by nslay** [comment] 2016-04-07 02:08
Would it be appropriate to merge the pull request? @siavashk has been unable to successfully test this module. 

I'm also missing a formal test and CMake magic to build/run the test and download the data.

**Comment by thewtex** [comment] 2016-04-07 15:29
I will merge the pull request.  Then, I will create a new pull request that adds continuous integration testing to the repository.  Then, hopefully others can gets the tests to pass and add more tests :-).

**Comment by nslay** [comment] 2016-04-07 16:36
Thanks Matthew,
I will try to write some tests later tonight.

Best regards,
Nathan Lay

**Comment by nslay** [comment] 2016-04-08 02:40
I've added a meta data test. Some of it was grafted from the example I wrote.
It took a lot longer than I expected since I wanted to compare console text. But --redirect-output appears to be broken and --compare and --compare-MD5 only operate on images. 

I plan to write a simple input/output test and a stream reading test afterward. I'll do those tomorrow or on the weekend.

**Comment by siavashk** [comment] 2016-04-11 19:05
@nslay @thewtex Sorry, I just got back from vacation yesterday. Will try to do more testing today.

**Closed as completed** 2016-04-18 04:15 UTC

**Comment by nslay** [comment] 2016-05-02 22:27
Matthew,
I've written the Insight Journal article today. I'm just checking if I need any kind of approval on my end.

**Comment by thewtex** [comment] 2016-05-02 23:20
@nslay That is great! Is there any large files like images? If so, I can create a separate repository in the InsightSoftwareConsortium GitHub organization. If not, we could merge it as a pull request to this repository in the doc/ directory.

**Comment by nslay** [comment] 2016-05-03 12:41
Hi Matthew,
There are no big images in the Insight Journal article. I just made a
subdirectory in my source tree called "journal." I'll change it to "doc."
Just waiting to see if approval is needed.

**Comment by thewtex** [comment] 2016-05-03 14:03
Hi Nathan,

That sounds great.  If you create a pull request, we can merge it here.  No approval is needed.  However, I am working on Python wrapping, and it would be nice to have that included in the article before it is submitted to the Insight Journal.

Thanks,
Matt

**Comment by nslay** [comment] 2016-05-03 19:16
No, the issue is that I normally have to follow proper channels within my
organization to publish something. Despite this being documentation, it
looks like I need to file a manuscript clearance form anyway.

No big deal. It will go through.

My supervisor also approved my contributing the source code to ITK.

**Comment by thewtex** [comment] 2016-05-03 19:26
Excellent :8ball:
